### ISSUE TITLE
Relative path to 'chrome.crx' extension breaks - bug

### ISSUE THREAD

**Issue by nfreear** [webdriverio/browserevent#1]
Hi @christian-bromann,

Thanks for your work on 'browserevent' and webdriver.io - v. useful!

The path provided at [line 35](https://github.com/webdriverio/browserevent/blob/master/lib/browserevent.js#L35) doesn't appear to work when browserevent is installed within another  project, that is, within `node_modules`:

```js
    this.crx = fs.readFileSync('./extensions/chrome.crx').toString('base64');
```

I don't yet have a fix. I'll submit something when I do...

(BTW, my [use case is here](https://github.com/nfreear/ou-media-player-test).)

Best wishes,

Nick

**Comment by christian-bromann** [comment]
Hi @nfreear 

thanks for reporting this issue. I changed the path and I am now using `__dirname` which should resolve to the right directory. Published new version to NPM. Please let me know if it works and reopen this issue if not.

Thanks!

**Comment by nfreear** [comment]
Hi Christian,

You beat me to it! Thank you for the quick resolution - it works great.

Best wishes,

Nick
