### ISSUE TITLE
 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by kgish** [webdriverio/browserevent#7]
I followed the instructions for installing the plugin, but when I start the tests I get the following error:

```
ERROR: Cannot set property 'removeEventListener' of undefined
```

**Comment by rajivsavroop** [comment]
@kgish browserevent isn't compatible with webdriverio v 3.0 and onwards. and current version is 4.0.7.

**Comment by christian-bromann** [comment]
This is correct. It's on the roadmap though as it might be interesting for people testing Atom apps
